sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t minwoojung93/docker-react-app -f Dockerfile.dev .

script: 
  - docker run -e CI=true minwoojung93/docker-react-app npm run test -- --coverage

after_success: -- after success test
	- echo "Test Success"

  deploy:
  edge: true
  provider: elasticbeanstalk 
  region: us-west-2 
  app:  react_docker_app
  env: Reactdockerapp-env
  bucket_name: elasticbeanstalk-us-west-2-066515780521 
  bucket_path:  react_docker_app
  on:
    branch: main 
  access_key_id: $aws_access_key
  secret_access_key: $aws_secret_access_key