sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t minwoojung93/docker-react-app -f Dockerfile.dev .

script: 
  - docker run -e CI=true minwoojung93/docker-react-app npm run test -- --coverage

after_success: -- after success test
	- echo "Test Success"